# steps:
#   - name: 'gcr.io/cloud-builders/gcloud'
#     args: ['app', 'deploy']

#   - name: 'python'
#     entrypoint: 'python3'
#     args: ['init_db.py']
steps:
  # Pasul 1: Construiește imaginea Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/simple-flask-api', '.']

  # Pasul 2: Încarcă imaginea Docker în Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/simple-flask-api']

  # Pasul 3: Desfășoară imaginea pe App Engine
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', '--image-url=gcr.io/$PROJECT_ID/simple-flask-api']
